### ISSUE TITLE
Implementation Advise

### ISSUE THREAD

**Issue by satyakirankumar** [CONNECT-Solution/CONNECT#1393]
Hi,

I want to implement the esMD implementation by using the CONNECT software. Currently, Our Solution is developed in Microsoft .NET Technologies (C# & ASP.NET). I do not know how to proceed on this Implementation, If anyone can give some ideas or any useful URL's on this implementation approach will be very helpful for me.

Thanks & Regards,
Satya

**Comment by sovanncgi** [comment]
Hi Satya, can you please post this question on http://forums.connectopensource.org/CONNECT-Installation-Issues-f3979355.html

Thanks!

Sovann

**Comment by vsaibabu** [comment]
Satya,

email me the logs to sai@wilmertech.com

Thanks,
Sai

**Comment by satyakirankumar** [comment]
Thank you very much Sovann and Sai for your responses.

Sai, 

For connect software, I have installed Java JDK, MySQL Database and Python. I have set the environment variables and configured JBOSS application server. Before going to set connect as service on JBOSS I have tried to integrate Connect WSDL’s into our .Net application.  I have downloaded connect binaries from the following url ftp://ftp.connectopensource.org/4.7.0/CONNECT-4.7.0-JB7.zip and then unzipped the file. I added WSDL files as web references which I got from unzipped file. But I am not able to see the exact methods or behaviors to communicate with connect gateway in order to get ready for ESMD phase 1 implementation process.

Can you please provide any reference or document to integrate connect software into our .Net application.?

Thanks & Regards,
 Satya

**Comment by vsaibabu** [comment]
Satya,

you are in a right direction. Downloading binaries and deploying them in
JBoss, running Validation Tests to make sure CONNECT installation is
successful is the correct way of setting up the software. I see your
problem is to implement the Adapters. There is a nice article here:
https://connectopensource.atlassian.net/wiki/display/CONNECTWIKI/Create+an+MPI+Adapter
. This will help you on how to implement DocumentSubmission Adapter for
your esMD project or an Entity Service implementation to initiate with ADR
information.

Now, how your implement is something your team should have expertise on it.
There are several ways to implement with in .Net Framework :-) , This is
something we can't guide here.

Hope this helps.

Thanks,
Sai Valluripalli
sai@wilmertech.com

**Comment by satyakirankumar** [comment]
Thank you very much Sai on Quick Reply.
