### ISSUE TITLE
COMMIT TODAY Breaks Production Build 

### ISSUE THREAD

**Issue by ddecouteau** [CONNECT-Solution/CONNECT#1827]
Your changes in gov.hhs.fha.nhinc.common.eventcommon causes Connect Core Library build to fail.

Reactor Summary:
[INFO] 
[INFO] Production ......................................... SUCCESS [  1.368 s]
[INFO] Common ............................................. SUCCESS [  0.011 s]
[INFO] Properties ......................................... SUCCESS [  0.511 s]
[INFO] CONNECT Core Library ............................... FAILURE [  5.513 s]
[INFO] Services ........................................... SKIPPED
[INFO] CONNECT Audit Repository Core ...................... SKIPPED
[INFO] CONNECT Audit Repository EJB ....................... SKIPPED
[INFO] CONNECT Connection Manager Core .................... SKIPPED
[INFO] CONNECT Document Repository Core ................... SKIPPED
[INFO] CONNECT Patient Correlation Core ................... SKIPPED
[INFO] CONNECT Policy Engine Core ......................... SKIPPED
[INFO] CONNECT Document Query Core ........................ SKIPPED
[INFO] CONNECT Document Registry Core ..................... SKIPPED
[INFO] CONNECT Patient Discovery Core ..................... SKIPPED
[INFO] CONNECT Document Data Submission Core .............. SKIPPED
[INFO] CONNECT Document Submission Core ................... SKIPPED
[INFO] CONNECT CORE X12 Document Submission Core .......... SKIPPED
[INFO] CONNECT Document Retrieve Core ..................... SKIPPED
[INFO] CONNECT Admin Distribution Core .................... SKIPPED
[INFO] Adapters ........................................... SKIPPED
[INFO] General ............................................ SKIPPED
[INFO] CONNECT Adapter Web ................................ SKIPPED
[INFO] CONNECT Deferred Queue Manager GUI ................. SKIPPED
[INFO] CONNECTDirectConfig ................................ SKIPPED
[INFO] CONNECT Adapter - AdminDistribution_a0 ............. SKIPPED
[INFO] CONNECT Adapter - DocumentQuery_a0 ................. SKIPPED
[INFO] CONNECT Adapter - DocumentRetrieve_a0 .............. SKIPPED
[INFO] CONNECT Adapter - DocumentSubmission_a0 ............ SKIPPED
[INFO] CONNECT Adapter - DocumentDataSubmission_a0 ........ SKIPPED
[INFO] CONNECT Adapter - PatientDiscovery_a0 .............. SKIPPED
[INFO] CONNECT Adapter - CORE_X12DocumentSubmission_a0 .... SKIPPED
[INFO] Gateway ............................................ SKIPPED
[INFO] CONNECT Gateway - AdminDistribution_10 ............. SKIPPED
[INFO] CONNECT Gateway - AdminDistribution_20 ............. SKIPPED
[INFO] CONNECT Gateway - DocumentQuery_20 ................. SKIPPED
[INFO] CONNECT Gateway - DocumentQuery_30 ................. SKIPPED
[INFO] CONNECT Gateway - DocumentRetrieve_20 .............. SKIPPED
[INFO] CONNECT Gateway - DocumentRetrieve_30 .............. SKIPPED
[INFO] CONNECT Gateway - DocumentSubmission_11 ............ SKIPPED
[INFO] CONNECT Gateway - DocumentSubmission_20 ............ SKIPPED
[INFO] CONNECT Gateway - PatientDiscovery_10 .............. SKIPPED
[INFO] CONNECT Gateway Web Webapp ......................... SKIPPED
[INFO] CONNECT Gateway - CORE_X12DocumentSubmission_10 .... SKIPPED
[INFO] CONNECT Gateway - DocumentDataSubmission_10 ........ SKIPPED
[INFO] CONNECT Gateway - CONNECTCommonWeb ................. SKIPPED
[INFO] CONNECT Deployment ................................. SKIPPED
[INFO] CONNECT JBoss7 EAR ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by TabassumJafri** [comment]
We have removed unused schema and webservices from CONNECT-Solution/Common-types and CONNECT-Solution/CONNECT-Webservices today.  Getting the latest from these repos will fix the build.

**Comment by TabassumJafri** [comment]
Can you also try building CONNECT with mvn -U  option. It will force to update all snapshot from public repo.

**Comment by ddecouteau** [comment]
Your previous email directions fixed problem..u can close issue

**Comment by TabassumJafri** [comment]
The issues was fixed after updating Common-types and CONNECT-Webservices project.
