### ISSUE TITLE
Where to set absolute path for Connect Lib

### ISSUE THREAD

**Issue by Nagasam123** [CONNECT-Solution/CONNECT#1935]
hi,

I am getting error "  Unable to determine the path to the configuration files.  Please make sure that the runtime nhinc.properties.dir system property is set to the absolute location of your CONNECT configuration files." 

Where to set the path ?

Thanks

**Comment by plobre** [comment]
Hello,

The properties directory location is defined by you, the user. This should point to the CONNECT property files included with the CONNECT source, as well as inside the binary zip file.

There are a number of different installation instructions for the servers we support. As an example, here is the relevant instructions for Wildfly / JBOSS: https://connectopensource.atlassian.net/wiki/spaces/CW/pages/775127289/Deploying+CONNECT+to+WildFly+8.2.1#DeployingCONNECTtoWildFly8.2.1-CONNECTpropertiesdirectorymodulesetup

The contents of this folder should be the included properties/configuration files: https://github.com/CONNECT-Solution/CONNECT/tree/CONNECT_integration/Product/Production/Common/Properties/src/main/resources

Thanks,
plobre
